name: Elexon Update Dataset - Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Every midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variable for credentials
        run: echo "ELEXON_SECRETS_AS=${{ secrets.ELEXON_SECRETS_AS }}" >> $GITHUB_ENV

      - name: Load energy generation data into BigQuery
        run: python bigquery.py

      - name: Load temperature and demand data into BigQuery
        run: python bigquery_temperature.py
